# Generated by Django 3.1 on 2020-11-02 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(choices=[('', 'Wybierz szkołę'), ('ps', 'Szkoła Podstawowa'), ('ms', 'Szkoła Średnia'), ('cl', 'Studia')], default='', max_length=2)),
                ('subject', models.CharField(choices=[('', 'Wybierz przedmiot'), ('mat', 'Matematyka'), ('fiz', 'Fizyka'), ('inf', 'Informatyka'), ('pol', 'Język Polski'), ('ang', 'Język Angielski'), ('nmc', 'Język Niemiecki'), ('his', 'Historia'), ('bio', 'Biologia'), ('che', 'Chemia'), ('geo', 'Geografia')], default='', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
