# Generated by Django 3.1 on 2020-11-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='school',
            field=models.CharField(choices=[('ps', 'Szkoła Podstawowa'), ('ms', 'Szkoła Średnia'), ('cl', 'Studia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('mat', 'Matematyka'), ('fiz', 'Fizyka'), ('inf', 'Informatyka'), ('pol', 'Język Polski'), ('ang', 'Język Angielski'), ('nmc', 'Język Niemiecki'), ('his', 'Historia'), ('bio', 'Biologia'), ('che', 'Chemia'), ('geo', 'Geografia')], max_length=3),
        ),
    ]
